### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by HonmaSakura** [syccxcc/Bilibili-AutoSub#3]
indowsPath('data/merged.flv')]
ERROR:root:None
None
Traceback (most recent call last):
  File "E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib\utils\subprocess_utils.py", line 14, in run_subprocess
    p.check_returncode()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['ffmpeg', '-loglevel', 'error', '-f', 'concat', '-safe', '0', '-i', WindowsPath('data/temp/files.txt'), '-c', 'copy', WindowsPath('data/merged.flv')]' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib\process_recording.py", line 174, in <module>
    main()
  File "E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib\process_recording.py", line 170, in main
    split_final_video()
  File "E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib\process_recording.py", line 127, in split_final_video
    execute_if_not_exist(config.final_video, create_final_video)
  File "E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib\utils\file_utils.py", line 16, in execute_if_not_exist
    func(**params)
  File "E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib\process_recording.py", line 120, in create_final_video
    execute_if_not_exist(config.merged_video, merge_videos, exit_if_fail=True)
  File "E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib\utils\file_utils.py", line 16, in execute_if_not_exist
    func(**params)
  File "E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib\process_recording.py", line 86, in merge_videos
    run_subprocess(["ffmpeg", "-loglevel", "error",
  File "E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib\utils\subprocess_utils.py", line 20, in run_subprocess
    logging.error("\n".join(traceback.format_exception(subprocess.CalledProcessError)))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\traceback.py", line 138, in format_exception
    value, tb = _parse_value_tb(exc, value, tb)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\traceback.py", line 104, in _parse_value_tb
    raise TypeError(f'Exception expected for value, '
TypeError: Exception expected for value, type found

E:\DM\Bilibil-AutoDanmaku_v1.0.0_windows-lib>echo "Program terminated. "

**Comment by HonmaSakura** [comment]
似乎是请求ffmpeg的时候出错了，但具体不清楚什么原因
